# Generated by Django 5.2.6 on 2025-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.CharField(choices=[('aberta', 'ABERTA'), ('em andamento', 'EM ANDAMENTO'), ('cancelado', 'CANCELADO'), ('concluido', 'CONCLUIDO')], default='aberta', max_length=12),
        ),
    ]
